apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clientes-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /src;/pom.xml;/Dockerfile;/templates;/Chart.yaml;/values.yaml

spec:
  project: default

  source:
    repoURL: https://github.com/TiffanyContreras/pruebaClaro.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - TimeoutSeconds=900
